# Generated by Django 3.2.5 on 2021-09-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='reply',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
